MEMORY
{
    FLASH (rx) : ORIGIN = 0x08000000, LENGTH = 128K
    RAM (rwx) : ORIGIN = 0x20000000, LENGTH = 20K
}

__reset_stack_pointer = ORIGIN(RAM) + LENGTH(RAM);

SECTIONS
{
    .text : {
        /* Set the initial address to 0 */
        . = 0;
        LONG(__reset_stack_pointer);
        LONG(Reset_Handler | 1);
        /* skip to end of vector table */
        . = 332;
        /* place the reset of the code */
        *(.text*)
    } > FLASH /* Put this in the flash memory region */
}